### ISSUE TITLE
ng-admin debug mode

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp_admin#68]
ng-admin currently compiled and minified with all possible dependencies. I think having some sort of debug mode, when sources of ng-admin are readable, could be very helpful. 

@goliney is it possible to build ng-admin without minification or attach source maps somehow?

**Comment by goliney** [comment]
It's shipped with [source-maps](https://github.com/aio-libs/aiohttp_admin/blob/master/aiohttp_admin/static/js/ng-admin/ng-admin.min.js.map).

In order to be able to use source maps you have to enable them first:
![image](https://cloud.githubusercontent.com/assets/2017344/19401897/8958ea5c-9266-11e6-9131-2647aacf7d4b.png)

**Comment by jettify** [comment]
Good, then we all set here.
